name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Step 1: Install dependencies in frontend directory
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      # Step 2: Build the project in frontend directory
      - name: Build
        working-directory: ./frontend
        run: npm run build

      # Step 3: Deploy with correct entry point
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FINANCE_MANAGEMENT_7C778 }}
          channelId: live
          projectId: finance-management-7c778
          entryPoint: ./frontend  # Specifica la cartella del frontend
